<x-layout>
    <x-registro.form
        :titulo="'Test'"
        :rotaProcessamento=`registroFixo.store`
        :tipos=$tipos
        :metodos=$metodos
        :formas=$formas
        :importancias=$importancias
        :categorias=$categorias
        :localizacaos=$localizacaos
        :realizadores=$realizadores
    />
</x-layout>
